#!/usr/bin/env python3
"""
generate_report.py
===================
Assemble all pipeline results into a final Markdown report and a
machine-readable JSON summary.

The report includes:
  - Executive summary (type call, confidence, latency)
  - Methods overview
  - Results: coverage comparison, SNP concordance, recombination,
    transcriptome overview
  - Figures (embedded as references)
  - Limitations and recommendations

Inputs (via snakemake):
  - latency_json, typing_json, recomb_json
  - gene_expression_tsv
  - barplot, piechart, coverage_plot, region_comparison (figure paths)
  - ebv1_stats, ebv2_stats (alignment summary files)
"""

import json
import os
import sys
from datetime import datetime

import pandas as pd


def read_alignment_stats(path):
    """Read HISAT2 alignment summary file."""
    stats = {}
    try:
        with open(path) as fh:
            for line in fh:
                line = line.strip()
                if ':' in line:
                    key, val = line.rsplit(':', 1)
                    stats[key.strip()] = val.strip()
    except Exception:
        stats = {'error': 'could not read stats file'}
    return stats


def format_type_name(t):
    """Format type name for display."""
    if t == 'type1':
        return 'Type 1 (EBV-1)'
    elif t == 'type2':
        return 'Type 2 (EBV-2)'
    elif t == 'ambiguous':
        return 'Ambiguous'
    elif t == 'undetermined':
        return 'Undetermined'
    return t


def format_confidence(c):
    """Format confidence level."""
    labels = {
        'high': 'High',
        'medium': 'Medium',
        'low': 'Low',
        'insufficient': 'Insufficient',
    }
    return labels.get(c, c)


def main():
    sample = snakemake.wildcards.sample

    # Load all results
    with open(snakemake.input.latency_json) as fh:
        latency = json.load(fh)
    with open(snakemake.input.typing_json) as fh:
        typing = json.load(fh)
    with open(snakemake.input.recomb_json) as fh:
        recomb = json.load(fh)

    # Read alignment stats
    ebv1_stats = read_alignment_stats(snakemake.input.ebv1_stats)
    ebv2_stats = read_alignment_stats(snakemake.input.ebv2_stats)

    # Read gene expression
    expr_df = pd.read_csv(snakemake.input.gene_expression_tsv, sep='\t')

    # Get figure paths (relative to results/ for the report)
    barplot_name = os.path.basename(snakemake.input.barplot)
    piechart_name = os.path.basename(snakemake.input.piechart)
    coverage_name = os.path.basename(snakemake.input.coverage_plot)
    region_name = os.path.basename(snakemake.input.region_comparison)

    # ------------------------------------------------------------------
    # Build Markdown report
    # ------------------------------------------------------------------
    report = []
    report.append(f"# EBV Type Identification Report — Sample: {sample}")
    report.append("")
    report.append(f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    report.append("")

    # Executive summary
    report.append("## Executive Summary")
    report.append("")
    ebv_type = format_type_name(typing.get('ebv_type', 'unknown'))
    confidence = format_confidence(typing.get('confidence', 'unknown'))
    latency_type = latency.get('latency_type', 'unknown')
    total_reads = latency.get('total_ebv_reads', 0)

    report.append(f"| Field | Value |")
    report.append(f"|-------|-------|")
    report.append(f"| **EBV Type** | **{ebv_type}** |")
    report.append(f"| **Confidence** | {confidence} |")
    report.append(f"| **Latency Type** | {latency_type} |")
    report.append(f"| **Total EBV Reads** | {total_reads:,} |")
    report.append(f"| **Typing Strategy** | {typing.get('typing_strategy', 'N/A')} |")
    report.append(f"| **Recombination** | {recomb.get('recombination_status', 'N/A')} |")
    report.append("")
    report.append(f"**Reasoning:** {typing.get('reason', 'N/A')}")
    report.append("")

    # Methods overview
    report.append("## Methods Overview")
    report.append("")
    report.append("This report was generated by the EBV Type Identification Pipeline,")
    report.append("which classifies EBV as type 1 or type 2 from RNA-seq data using two")
    report.append("complementary approaches:")
    report.append("")
    report.append("1. **Dual-reference alignment:** RNA-seq reads (after human read")
    report.append("   filtering) are aligned independently to the EBV-1 reference")
    report.append("   (NC_007605.1, B95-8 strain) and the EBV-2 reference")
    report.append("   (NC_009334.1, AG876 strain). Reads from a type-1 infection align")
    report.append("   better to the EBV-1 reference, especially in divergent regions")
    report.append("   (EBNA2, EBNA3 family).")
    report.append("")
    report.append("2. **SNP concordance scoring:** At positions where the EBV-1 and")
    report.append("   EBV-2 reference genomes differ, the allele observed in the")
    report.append("   alignment is compared to both reference bases. The type with")
    report.append("   higher concordance indicates the infecting type.")
    report.append("")
    report.append("Latency type is assessed from the expression pattern of EBV latent")
    report.append("genes (EBNA1, EBNA2, EBNA3A/3B/3C, LMP1, LMP2A, EBER1/2).")
    report.append("")

    # Alignment statistics
    report.append("## Alignment Statistics")
    report.append("")
    report.append("| Reference | Alignment Summary |")
    report.append("|-----------|-------------------|")
    report.append(f"| EBV-1 (NC_007605.1) | {ebv1_stats.get('overall alignment rate', 'N/A')} |")
    report.append(f"| EBV-2 (NC_009334.1) | {ebv2_stats.get('overall alignment rate', 'N/A')} |")
    report.append(f"| EBV-1 total reads | {latency.get('ebv1_total_reads', 0):,} |")
    report.append(f"| EBV-2 total reads | {latency.get('ebv2_total_reads', 0):,} |")
    report.append("")

    # Coverage scoring
    report.append("## Coverage-Based Scoring")
    report.append("")
    cov = typing.get('coverage_scoring', {})
    report.append("Read counts in type-discriminatory regions (EBV-1 vs EBV-2 alignment):")
    report.append("")
    report.append("| Gene | Reads (EBV-1 ali) | Reads (EBV-2 ali) | log2 Ratio | Vote |")
    report.append("|------|-------------------|-------------------|------------|------|")
    for gene, info in cov.get('per_gene', {}).items():
        lr = info.get('log2_ratio')
        lr_str = f"{lr:.3f}" if lr is not None else "N/A"
        report.append(
            f"| {gene} | {info.get('reads_ebv1', 0):,} | "
            f"{info.get('reads_ebv2', 0):,} | {lr_str} | "
            f"{info.get('vote', 'N/A')} |"
        )
    report.append("")
    report.append(f"**Overall log2 ratio:** {cov.get('overall_log2_ratio', 'N/A')}")
    report.append(f"**Coverage-based call:** {format_type_name(cov.get('call', 'N/A'))}")
    report.append(f"**Type-1 votes:** {cov.get('type1_votes', 0)} | "
                  f"**Type-2 votes:** {cov.get('type2_votes', 0)}")
    report.append("")

    # SNP concordance
    report.append("## SNP Concordance Scoring")
    report.append("")
    snp = typing.get('snp_concordance', {})
    report.append("| Field | Value |")
    report.append("|-------|-------|")
    report.append(f"| Callable type-specific SNPs | {snp.get('callable_snps', 0)} |")
    report.append(f"| Type-1 concordant | {snp.get('type1_concordant', 0)} |")
    report.append(f"| Type-2 concordant | {snp.get('type2_concordant', 0)} |")
    report.append(f"| Type-1 fraction | {snp.get('type1_fraction', 0):.2%} |")
    report.append(f"| Type-2 fraction | {snp.get('type2_fraction', 0):.2%} |")
    report.append(f"| **SNP-based call** | **{format_type_name(snp.get('call', 'N/A'))}** |")
    report.append(f"| **Concordance score** | **{snp.get('concordance_score', 0):.2%}** |")
    report.append("")

    # Recombination
    report.append("## Recombination / Mixed Infection Analysis")
    report.append("")
    report.append(f"**Status:** {recomb.get('recombination_status', 'N/A')}")
    report.append("")
    if recomb.get('recombination_note'):
        report.append(f"**Note:** {recomb['recombination_note']}")
        report.append("")
    if recomb.get('bzlf1_note'):
        report.append(f"**BZLF1:** {recomb['bzlf1_note']}")
        report.append("")

    region_typing = recomb.get('region_typing', {})
    if region_typing:
        report.append("Per-region independent typing:")
        report.append("")
        report.append("| Region | SNP Call | Coverage Call | Callable SNPs |")
        report.append("|--------|----------|---------------|---------------|")
        for rname, rinfo in region_typing.items():
            sd = rinfo.get('snp_details', {})
            report.append(
                f"| {rname} | {rinfo.get('snp_call', 'N/A')} | "
                f"{rinfo.get('coverage_call', 'N/A')} | "
                f"{sd.get('callable_snps', 0)} |"
            )
        report.append("")

    # Latency assessment
    report.append("## Latency Assessment")
    report.append("")
    markers = latency.get('marker_expression', {})
    report.append("| Gene | TPM | Reads | Expressed |")
    report.append("|------|-----|-------|-----------|")
    for gene in ['EBNA2', 'EBNA3A', 'EBNA3B', 'EBNA3C', 'LMP1', 'LMP2A',
                 'EBNA1', 'EBER1', 'EBER2']:
        m = markers.get(gene, {})
        expr = 'Yes' if m.get('expressed') else 'No'
        report.append(
            f"| {gene} | {m.get('tpm', 0):.2f} | "
            f"{m.get('reads', 0):,} | {expr} |"
        )
    report.append("")
    report.append(f"**Lytic fraction:** {latency.get('lytic_fraction', 0):.1%}")
    report.append(f"**Latency classification:** {latency.get('latency_type', 'N/A')}")
    report.append(f"**Typing strategy used:** {latency.get('typing_strategy', 'N/A')}")
    report.append(f"**Note:** {latency.get('typing_note', 'N/A')}")
    report.append("")

    # Transcriptome overview
    report.append("## EBV Transcriptome Overview")
    report.append("")
    report.append(f"![Gene Expression]({barplot_name})")
    report.append("")
    report.append(f"![Latent vs Lytic]({piechart_name})")
    report.append("")
    report.append(f"![Genome Coverage]({coverage_name})")
    report.append("")
    report.append(f"![Region Coverage Comparison]({region_name})")
    report.append("")

    # Top expressed genes
    report.append("### Top Expressed EBV Genes")
    report.append("")
    report.append("| Gene | Count | TPM | Category |")
    report.append("|------|-------|-----|----------|")
    top_genes = expr_df.head(15)
    for _, row in top_genes.iterrows():
        report.append(
            f"| {row['gene']} | {int(row['count']):,} | "
            f"{row['tpm']:.2f} | {row['category']} |"
        )
    report.append("")

    # Limitations
    report.append("## Limitations and Recommendations")
    report.append("")
    report.append("1. **RNA-seq coverage dependency:** This pipeline relies on EBV-derived")
    report.append("   RNA-seq reads. If the cell line is in Latency I (EBNA2 not expressed),")
    report.append("   EBNA2-based typing is not possible and the pipeline falls back to")
    report.append("   EBNA3 or genome-wide SNP concordance with lower confidence.")
    report.append("")
    report.append("2. **Poly-A capture bias:** If the library was poly-A selected, non-poly-A")
    report.append("   transcripts (EBER1/2, some BART RNAs) will be underrepresented.")
    report.append("")
    report.append("3. **Recombination:** Intertypic recombinants are known to exist in EBV.")
    report.append("   The pipeline checks for EBNA2/EBNA3 type discordance, but complex")
    report.append("   recombinants may require whole-genome sequencing for full resolution.")
    report.append("")
    report.append("4. **Mixed infections:** If the cell line harbors both type 1 and type 2")
    report.append("   EBV, the pipeline will flag mixed signals but cannot fully resolve")
    report.append("   the proportion of each type from RNA-seq alone.")
    report.append("")
    report.append("5. **DNA-based confirmation:** For publication-grade results, confirm the")
    report.append("   RNA-seq-based call with EBNA2-targeted PCR and Sanger sequencing,")
    report.append("   which remains the gold standard for EBV typing.")
    report.append("")

    # References
    report.append("## References")
    report.append("")
    report.append("1. Tzellos S, Farrell PJ. Epstein-Barr Virus Sequence Variation—Biology")
    report.append("   and Disease. Pathogens. 2012;1(2):156-175.")
    report.append("2. Sample J et al. Epstein-Barr virus types 1 and 2 differ in their")
    report.append("   EBNA-3A, EBNA-3B, and EBNA-3C genes. J Virol. 1990;64(9):4084-4092.")
    report.append("3. Blazquez AC et al. A Comparative Genomic Analysis of Epstein-Barr")
    report.append("   Virus Strains with a Focus on EBV2 Variability. Int J Mol Sci.")
    report.append("   2025;26(6):2708.")
    report.append("4. Correia S et al. Sequence Variation of Epstein-Barr Virus: Viral")
    report.append("   Types, Geography, Codon Usage, and Diseases. J Virol. 2018;92(20).")
    report.append("5. Palser AL et al. Genome Diversity of Epstein-Barr Virus from")
    report.append("   Multiple Tumor Types and Normal Infection. J Virol. 2015;89(10).")
    report.append("6. Lin JC et al. Precision of genotyping of Epstein-Barr virus by")
    report.append("   polymerase chain reaction using three gene loci. Blood.")
    report.append("   1993;81(12):3372.")
    report.append("")

    # Write report
    report_text = '\n'.join(report)
    with open(snakemake.output.report, 'w') as out:
        out.write(report_text)

    # Write JSON summary
    summary = {
        'sample': sample,
        'timestamp': datetime.now().isoformat(),
        'ebv_type': typing.get('ebv_type'),
        'confidence': typing.get('confidence'),
        'latency_type': latency.get('latency_type'),
        'total_ebv_reads': latency.get('total_ebv_reads'),
        'typing_strategy': typing.get('typing_strategy'),
        'recombination_status': recomb.get('recombination_status'),
        'snp_concordance_score': typing.get('snp_concordance', {}).get('concordance_score'),
        'callable_snps': typing.get('snp_concordance', {}).get('callable_snps'),
        'coverage_log2_ratio': typing.get('coverage_scoring', {}).get('overall_log2_ratio'),
        'reason': typing.get('reason'),
    }
    with open(snakemake.output.summary_json, 'w') as out:
        json.dump(summary, out, indent=2)

    print(f"[generate_report] Report written to {snakemake.output.report}")
    print(f"[generate_report] Summary JSON written to {snakemake.output.summary_json}")


if __name__ == '__main__' or 'snakemake' in globals():
    if 'snakemake' in globals():
        main()
